### PR TITLE
fix: route tablet-aware batches via routed statement

### LINKED ISSUE #879: Token-aware batch routing uses wrong tablet metadata lookup context
### Broken behavior

Token-aware routing for `BatchStatement` can fail to use tablet metadata even when the batch has a valid routing key.

### Reproducer

1. Create a tablet-enabled keyspace and table.
2. Learn tablet metadata for the table.
3. Execute a `BatchStatement` containing a bound statement with a valid routing key.
4. Observe the hosts selected by `TokenAwarePolicy`.

Expected:

- the batch routing key and table name are derived from the same routed child statement;
- tablet replica lookup uses that table name;
- the query plan stays within the expected tablet replicas.

Actual:

- the batch exposes a routing key, but tablet table-name extraction is done from the outer batch statement context;
- `TokenAwarePolicy` cannot resolve the correct tablet table for the batch;
- routing can fall back instead of using tablet metadata.

### Cause

`TokenAwarePolicy` handled table-name extraction for direct `BoundStatement` and `PreparedStatement` inputs only. A `BatchStatement` needs an extra step: select the child statement that provides the routing key, then derive table metadata from that same child.

### Fix

Resolve batch routing metadata through the routed child statement and keep existing direct statement behavior unchanged.

### Verification

Covered by focused unit tests for `TokenAwarePolicy` and a CCM-backed tablet integration test using Scylla `release:2026.1`.

### Customer Reference

- CUSTOMER-323

### PR DESCRIPTION
**Pull request by dkropachev**
## Summary
- make `TokenAwarePolicy` derive tablet routing metadata from the same batch child statement that provides the routing key
- preserve the existing single-statement `BoundStatement` and `PreparedStatement` table-name handling
- add focused regression coverage for bound statements, batch statements, and the tablet-aware integration path

## Context
Batch statements on tablet keyspaces need both a routing key and the table name for tablet replica lookup. The previous implementation could get the routing key from a batch, but table-name extraction only handled direct `BoundStatement` / `PreparedStatement` inputs, so tablet-aware token routing could fall back instead of using tablet metadata.

Fixes #879
Fixes: https://scylladb.atlassian.net/browse/CUSTOMER-323

## Testing
- `mvn -pl driver-core -am -Dscylla.version=release:2026.1 -Dccm.version=release:2026.1 -Dccm.scylla=true -Dccm.distribution=scylla -Dtest=TokenAwarePolicyTest#should_use_table_name_from_bound_statement_for_tablet_routing+should_use_table_name_from_routed_statement_in_batch_for_tablet_routing test`
- `mvn -pl driver-core -am -Pshort -Dscylla.version=release:2026.1 -Dccm.version=release:2026.1 -Dccm.scylla=true -Dccm.distribution=scylla -Dtest=TabletsIT#batch_statement_should_deliver_tablet_info_and_route_properly test`

### CODE REVIEW

File: driver-core/src/main/java/com/datastax/driver/core/BatchStatement.java [hunk 1]
```diff
@@ -298,6 +295,24 @@ void ensureAllSet() {
       if (statement instanceof BoundStatement) ((BoundStatement) statement).ensureAllSet();
   }
 
+  /**
+   * Returns the first statement in this batch that can provide routing information.
+   *
+   * <p>This is primarily used by tablet-aware routing, which needs to derive both the routing key
+   * and the table name from the same batch entry.
+   */
+  public Statement getRoutingStatement(
```
Comment (nikagra) [inline driver-core/src/main/java/com/datastax/driver/core/BatchStatement.java:304]: 1. Is `public` an intended and proper visibility level?
2. `getRoutingKey` is called twice: one in here, and then immediately after (+1 use for `TokenAwarePolicy.newQueryPlan`)

File: driver-core/src/main/java/com/datastax/driver/core/BatchStatement.java
Comment (nikagra) [inline driver-core/src/main/java/com/datastax/driver/core/BatchStatement.java:278]: Consider fetching keyspace from the same child statement (reuse `getRoutingStatement`) so that key, keyspace and table sll come from the same source

File: driver-core/src/main/java/com/datastax/driver/core/policies/TokenAwarePolicy.java [hunk 2]
```diff
@@ -453,6 +445,27 @@ public Iterator<Host> newQueryPlan(final String loggedKeyspace, final Statement
...
   }
 
+  private String getRoutingTable(Statement statement) {
+    ColumnDefinitions defs = getRoutingVariables(statement);
+    return (defs == null || defs.size() == 0) ? null : defs.getTable(0);
+  }
+
+  private ColumnDefinitions getRoutingVariables(Statement statement) {
+    if (statement instanceof BatchStatement) {
+      statement = ((BatchStatement) statement).getRoutingStatement(protocolVersion, codecRegistry);
```
Comment (nikagra) [inline driver-core/src/main/java/com/datastax/driver/core/policies/TokenAwarePolicy.java]: I've missed this argument reassignment when read this code first, consider renaming the variable to highlight this. E.g., 
```suggestion
      Statement target = ((BatchStatement) statement).getRoutingStatement(protocolVersion, codecRegistry);
```
but more changes in method will be surely needed to apply this suggestion

**Comment by nikagra** [comment]
How does is routing table is used for _shard-aware connection borrowing_ as mentioned in PR description?

File: driver-core/src/main/java/com/datastax/driver/core/policies/TokenAwarePolicy.java (hunk 2 above)
Comment (dkropachev) [reply driver-core/src/main/java/com/datastax/driver/core/policies/TokenAwarePolicy.java]: nice catch, fixed.

File: driver-core/src/main/java/com/datastax/driver/core/BatchStatement.java
Comment (dkropachev) [reply driver-core/src/main/java/com/datastax/driver/core/BatchStatement.java:278]: Good idea, but i am dropping this change, there problem of `ProtocolVersion protocolVersion, CodecRegistry codecRegistry` being required for `getRoutingStatement`.
TBH, I am thinking now that it would be better to stick to first statement in the batch, but anyways, let's keep it for another PR.

File: driver-core/src/main/java/com/datastax/driver/core/BatchStatement.java (hunk 1 above)
Comment (dkropachev) [reply driver-core/src/main/java/com/datastax/driver/core/BatchStatement.java:304]: it has been dropped.

**Comment by dkropachev** [comment]
> How does is routing table is used for _shard-aware connection borrowing_ as mentioned in PR description?

it was left over from first implementation that included fixes for other edge cases of BatchStatement that I had dropped.

File: driver-core/src/main/java/com/datastax/driver/core/policies/TokenAwarePolicy.java [hunk 3]
```diff
@@ -453,6 +445,28 @@ public Iterator<Host> newQueryPlan(final String loggedKeyspace, final Statement
...
+    }
+
+    if (target instanceof BoundStatement) {
+      return ((BoundStatement) target).preparedStatement().getVariables();
+    } else if (target instanceof PreparedStatement) {
+      return ((PreparedStatement) target).getVariables();
+    }
+    return null;
+  }
+
```
Comment (Lorak-mmk) [inline driver-core/src/main/java/com/datastax/driver/core/policies/TokenAwarePolicy.java:469]: `keyspace` is retrieved with `getKeyspace` method. Why not introduce similar `getTable()`? `instanceof` matching seems like a weird choice here.

Comment (dkropachev) [reply driver-core/src/main/java/com/datastax/driver/core/policies/TokenAwarePolicy.java:469]: The problem is that there is already confusion in BatchStatement API https://github.com/scylladb/java-driver/blob/f621e3f649e7966fa512125e3348b9f0f9bcca2b/driver-core/src/main/java/com/datastax/driver/core/BatchStatement.java#L268-L283

As you can see both routing key and keyspace are extracted in completely different way, which means that it can pull key from one statement, keyspace from another statement and if I add table it might pull table from also from another statement.

It could be routed via getRoutingStatement, but then it would mean that both getTable and getKeyspace will get  `ProtocolVersion protocolVersion, CodecRegistry codecRegistry` params, which is not user would expect.

In order to solve all this confusion in efficient manner needs a major refactor of BatchStatement that has nothing to do with this PR.

Comment (Lorak-mmk) [reply driver-core/src/main/java/com/datastax/driver/core/policies/TokenAwarePolicy.java:469]: Imo the solution is to unify fetching routing info. Have a class like `RoutingInfo` with keyspace, table, token and other things that can influence lbp. For example here is def from Rust Driver after stripping comments:
```rust
/// Represents info about statement that can be used by load balancing policies.
#[derive(Default, Clone, Debug)]
#[non_exhaustive]
pub struct RoutingInfo<'a> {
    pub consistency: types::Consistency,
    pub serial_consistency: Option<types::SerialConsistency>,
    pub token: Option<Token>,
    pub table: Option<&'a TableSpec<'a>>,
    pub is_confirmed_lwt: bool,
}
```

Then have a `getRoutingInfo` method on `Statement`, so that each `Statement` subclass can define how to generate it, and have a single place for all the data.
Batch would just call `getRoutingInfo` of its first statement and return it.

But, as you mentioned, this is not a task for this PR.

Comment (dkropachev) [reply driver-core/src/main/java/com/datastax/driver/core/policies/TokenAwarePolicy.java:469]: https://github.com/scylladb/java-driver/issues/880#issuecomment-4327999421

**Review by Lorak-mmk — APPROVED** [review]
