### PR TITLE
Fix should_unset_flag_on_failed_agreement flakiness

### LINKED ISSUE #170: Integration test `SchemaAgreementTest.should_unset_flag_on_failed_agreement` is flaky
Seem that on branch enterprise-2022.2 tests `SchemaAgreementTest.should_unset_flag_on_failed_agreement` keep 
on failing with like:

```
23:57:25  Starting com.datastax.driver.core.SchemaAgreementTest.should_unset_flag_on_failed_agreement [Test #317]...
23:57:25  FAILED : should_unset_flag_on_failed_agreement
23:57:25  Test   : 00:00:00
23:57:25  Elapsed: 01:09:02
23:57:25  
23:57:25      4141961 [cluster5588-reconnection-1] ERROR com.datastax.driver.core.ControlConnection - [Control connection] Cannot connect to any host, scheduling retry in 512000 milliseconds
23:57:25      4141972 [cluster5588-nio-worker-19] WARN  com.datastax.driver.core.Connection - Error creating netty channel to /127.0.1.2:38783
23:57:25  io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.1.2:38783
23:57:25  	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
23:57:25  	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
23:57:25  	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:225)
23:57:25  	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:291)
23:57:25  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
23:57:25  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
23:57:25  	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
23:57:25  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
23:57:25  	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
23:57:25  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
23:57:25  	at java.lang.Thread.run(Thread.java:750)
23:57:25  Caused by: java.net.ConnectException: Connection refused
23:57:25  	... 11 more
23:57:30      4145646 [main] WARN  com.datastax.driver.core.CCMBridge - Executing: ccm stop --config-dir=/tmp/1667511261457-0
23:57:30      4146268 [main] INFO  com.datastax.driver.core.CCMBridge - Error during tests, kept C* logs in /tmp/1667511261457-0
23:57:30  [ERROR] Tests run: 326, Failures: 1, Errors: 0, Skipped: 12, Time elapsed: 4,148.029 s <<< FAILURE! - in TestSuite
23:57:30  [ERROR] should_unset_flag_on_failed_agreement(com.datastax.driver.core.SchemaAgreementTest)  Time elapsed: 0.01 s  <<< FAILURE!
23:57:30  com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)
23:57:30  	at com.datastax.driver.core.SchemaAgreementTest.should_unset_flag_on_failed_agreement(SchemaAgreementTest.java:55)
23:57:30  Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)
23:57:30  	at com.datastax.driver.core.SchemaAgreementTest.should_unset_flag_on_failed_agreement(SchemaAgreementTest.java:55)
23:57:30  
23:57:30      4146330 [Thread-76] WARN  com.datastax.driver.core.CCMBridge - Executing: ccm stop --config-dir=/tmp/1667511790109-0
23:57:30      4146331 [Thread-80] WARN  com.datastax.driver.core.CCMBridge - Executing: ccm stop --config-dir=/tmp/1667512049589-0
23:57:33      4149960 [Thread-80] WARN  com.datastax.driver.core.CCMBridge - Executing: ccm remove --config-dir=/tmp/1667512049589-0
23:57:33      4149965 [Thread-76] WARN  com.datastax.driver.core.CCMBridge - Executing: ccm remove --config-dir=/tmp/1667511790109-0
23:57:36  [INFO] 
23:57:36  [INFO] Results:
23:57:36  [INFO] 
23:57:36  [ERROR] Failures: 
23:57:36  [ERROR]   SchemaAgreementTest.should_unset_flag_on_failed_agreement:55 ? NoHostAvailable
23:57:36  [INFO] 
23:57:36  [ERROR] Tests run: 323, Failures: 1, Errors: 0, Skipped: 9
```

https://jenkins.scylladb.com/job/enterprise-2022.2/job/driver-tests/job/java-driver-matrix-test/8/console
https://jenkins.scylladb.com/job/enterprise-2022.2/job/driver-tests/job/java-driver-matrix-test/7/console
https://jenkins.scylladb.com/job/enterprise-2022.2/job/driver-tests/job/java-driver-matrix-test/6/console

seems like cluster with node 127.0.1.2:38783, is being used in some tests before, and it's not in a health state

this test seems to be working in master and 5.1 just fine:
https://jenkins.scylladb.com/job/scylla-master/job/driver-tests/job/java-driver-matrix-test/894/testReport/3.7.1-scylla-2.com.datastax.driver.core/SchemaAgreementTest/should_unset_flag_on_failed_agreement/history/
 https://jenkins.scylladb.com/view/scylla-5.1/job/scylla-5.1/job/driver-tests/job/java-driver-matrix-test/7/console

### PR DESCRIPTION
**Pull request by avelanarius**
This PR aims to fix flakiness of `should_unset_flag_on_failed_agreement` test (as seen in #170).

Firstly, during investigation of the issue, it was discovered that an unrelated test had missing `dirtiesContext = true` configuration in `@CCMConfig` of `ControlConnectionTest.should_prevent_simultaneous_reconnection_attempts`. That test stops cluster nodes: `ccm().stop(1)`, so it requires `dirtiesContext = true`. Even though the test class itself had this option correctly set, the test method annotation overwrote this configuration. Depending on the order of tests, this could cause another test to fail, as all of the nodes of cluster were removed.

Next, a d962bf603682ed0e8b8defc01f2a99643b79320b commit was reverted. That commit tried to deal with the fact, that  `should_unset_flag_on_failed_agreement` would leave the schema in  disagreement. If another test ran after that one, it would start with schema in disagreement. 

The previous solution was to set `priority=1`, so that this test would run after other tests. The problem with that solution is that all other tests from SchemaAgreementTests would run at one moment, then some unrelated tests would run and finally `should_unset_flag_on_failed_agreement` would run. Those unrelated tests could screw up the execution of `should_unset_flag_on_failed_agreement`, as seen in #170.

The final commit fixes that problem by running a dummy query with long schema agreement timeout, so that after this test runs, the schema is in agreement and the state of affairs is clean and `priority=1` fix is no longer needed.

Fixes #170

### CODE REVIEW

**Comment by avelanarius** [comment]
I looked at all other tests with `ccm().stop(...)` and it looks like all others have `dirtiesContext` correctly set.

**Comment by avelanarius** [comment]
~~Actually it looks like this fix is not sufficient: we also need to fix the problem that `should_unset_flag_on_failed_agreement` is executed much later compared to other tests in `SchemaAgreementTest` - so even though `should_prevent_simultaneous_reconnection_attempts` has correct `dirtiesContext`, once the execution returns to  `should_unset_flag_on_failed_agreement` `CCMTestsSupport` does not check if it has to re-create CCM cluster.~~

Fixed in v2.

**Comment by avelanarius** [comment]
v2: Addressed the previous "Actually it looks like this fix is not sufficient" comment.

Two commits were added ("Revert..." and "Wait for agreement...").

File: driver-core/src/test/java/com/datastax/driver/core/SchemaAgreementTest.java [hunk 1]
```diff
@@ -47,7 +47,7 @@ public void should_set_flag_on_non_schema_altering_statement() {
     assertThat(rs.getExecutionInfo().isSchemaInAgreement()).isTrue();
   }
 
-  @Test(groups = "short", priority = 1)
+  @Test(groups = "short")
```
Comment (Lorak-mmk) [inline driver-core/src/test/java/com/datastax/driver/core/SchemaAgreementTest.java:50]: The original commit message says:
```
This test should run last as it makes a schema change and then
immediately checks schema agreement.  Subsequent tests that run, such as
should_check_agreement_through_cluster_metadata may observe schemas
don't agree when they run at fail.
```

So, let's say that this test fails - can't this cause failure of other tests?
