### PR TITLE
4.x: Fix tablet update for non-select queries

### LINKED ISSUE #500: Tablets are not updated for every type of query except select
Currently code that updates tablets on response: https://github.com/scylladb/java-driver/blob/e5cb7d6b67dcdbced72a12582845647d046099ec/core/src/main/java/com/datastax/oss/driver/internal/core/cql/CqlRequestHandler.java#L476-L487

Which requires `resultSet.getColumnDefinitions().size() > 0 ` for tablets to be updated and only select queries have that.
As result, only `SELECT` queries are getting tablets updated on session.

### PR DESCRIPTION
**Pull request by dkropachev**
Before fix:
```
java.lang.AssertionError: Found queries that got no tablet info: 
Statement DELETE_CK_CONCRETE_PREPARED on session REGULAR did not trigger session tablets update
Statement INSERT_CK_CONCRETE_PREPARED on session REGULAR did not trigger session tablets update
Statement UPDATE_PREPARED on session REGULAR did not trigger session tablets update
Statement INSERT_PREPARED on session REGULAR did not trigger session tablets update
Statement DELETE_PREPARED on session REGULAR did not trigger session tablets update
Statement UPDATE_CK_CONCRETE_PREPARED on session REGULAR did not trigger session tablets update
Statement UPDATE_NO_KS_PREPARED on session USE_KEYSPACE did not trigger session tablets update
Statement DELETE_CK_CONCRETE_PREPARED on session USE_KEYSPACE did not trigger session tablets update
Statement INSERT_NO_KS_PREPARED on session USE_KEYSPACE did not trigger session tablets update
Statement INSERT_CK_CONCRETE_PREPARED on session USE_KEYSPACE did not trigger session tablets update
Statement UPDATE_PREPARED on session USE_KEYSPACE did not trigger session tablets update
Statement INSERT_PREPARED on session USE_KEYSPACE did not trigger session tablets update
Statement DELETE_PREPARED on session USE_KEYSPACE did not trigger session tablets update
Statement DELETE_NO_KS_PREPARED on session USE_KEYSPACE did not trigger session tablets update
Statement UPDATE_CK_CONCRETE_PREPARED on session USE_KEYSPACE did not trigger session tablets update
Statement UPDATE_NO_KS_PREPARED on session WITH_KEYSPACE did not trigger session tablets update
Statement DELETE_CK_CONCRETE_PREPARED on session WITH_KEYSPACE did not trigger session tablets update
Statement INSERT_NO_KS_PREPARED on session WITH_KEYSPACE did not trigger session tablets update
Statement INSERT_CK_CONCRETE_PREPARED on session WITH_KEYSPACE did not trigger session tablets update
Statement UPDATE_PREPARED on session WITH_KEYSPACE did not trigger session tablets update
Statement INSERT_PREPARED on session WITH_KEYSPACE did not trigger session tablets update
Statement DELETE_PREPARED on session WITH_KEYSPACE did not trigger session tablets update
Statement DELETE_NO_KS_PREPARED on session WITH_KEYSPACE did not trigger session tablets update
Statement UPDATE_CK_CONCRETE_PREPARED on session WITH_KEYSPACE did not trigger session tablets update
```

Fixes: https://github.com/scylladb/java-driver/issues/500

### CODE REVIEW

**Comment by dkropachev** [comment]
By some reason`TabletMapSchemaChangesIT` start failing, diggin into it.

File: core/src/main/java/com/datastax/oss/driver/internal/core/cql/CqlRequestHandler.java [hunk 1]
```diff
@@ -473,17 +473,31 @@ private void setFinalResult(
...
+          if (keyspace == null) {
+            keyspace = resultSet.getExecutionInfo().getRequest().getKeyspace();
+            if (keyspace == null && resultSet.getColumnDefinitions().size() > 0) {
+              keyspace = resultSet.getColumnDefinitions().get(0).getKeyspace();
+            }
+          }
+
+          CqlIdentifier table = resultSet.getExecutionInfo().getRequest().getRoutingTable();
+          if (table == null) {
+            table = resultSet.getExecutionInfo().getRequest().getKeyspace();
```
Comment (Bouncheck) [inline core/src/main/java/com/datastax/oss/driver/internal/core/cql/CqlRequestHandler.java]: This should not be set to keyspace

**Review by Bouncheck — CHANGES_REQUESTED** [review]

File: core/src/main/java/com/datastax/oss/driver/internal/core/cql/CqlRequestHandler.java (hunk 1 above)
Comment (dkropachev) [reply core/src/main/java/com/datastax/oss/driver/internal/core/cql/CqlRequestHandler.java]: removed.

**Comment by dkropachev** [comment]
Regarding `TabletMapSchemaChangesIT`, failure not related to this fix, there is another bug somewhere else.
Most-likely it is https://github.com/scylladb/java-driver/pull/505, let's merge that one, rebase and see if it passes.

**Review by Bouncheck — APPROVED** [review]

**Comment by dkropachev** [comment]
@Bouncheck , as I guessed failures were fixed by https://github.com/scylladb/java-driver/pull/505
