### PR TITLE
4.x: Allow BatchStatements to be LWT

### LINKED ISSUE #488: Missing LWT routing for batch statements
The following test modified to use batch statement fails with both Scylla 6.2.0 and 5.4.0:
```
public void should_use_only_one_node_when_lwt_detected() {
    assumeTrue(CcmBridge.SCYLLA_ENABLEMENT); // Functionality only available in Scylla
    CqlSession session = SESSION_RULE.session();
    int pk = 1234;
    ByteBuffer routingKey = TypeCodecs.INT.encodePrimitive(pk, ProtocolVersion.DEFAULT);
    TokenMap tokenMap = SESSION_RULE.session().getMetadata().getTokenMap().get();
    Node owner = tokenMap.getReplicas(session.getKeyspace().get(), routingKey).iterator().next();
    PreparedStatement statement =
        SESSION_RULE
            .session()
            .prepare("INSERT INTO foo (pk, ck, v) VALUES (?, ?, ?) IF NOT EXISTS");

    assertThat(statement.isLWT()).isTrue();
    for (int i = 0; i < 30; i++) {
      BatchStatementBuilder batchStatementBuilder = new BatchStatementBuilder(BatchType.LOGGED);
      batchStatementBuilder.addStatement(statement.bind(pk, i, 123));
      ResultSet result = session.execute(batchStatementBuilder.build());
      assertThat(result.getExecutionInfo().getCoordinator()).isEqualTo(owner);
    }
  }
```
This batch statement is not seen by the driver as LWT and routes it to the other nodes, likely in the same manner as any other regular query.
If it's possible the driver should treat this example as LWT and in general if it's not possible (e.g. if driver allows multiple LWT statements with different PK's in a batch) then should throw or warn.

Related core issue: https://github.com/scylladb/scylla-enterprise/issues/5331

### PR DESCRIPTION
**Pull request by Bouncheck**
Previously all DefaultBatchStatements would always return `false` when `isLWT()` was called. This would cause the driver to route the batch based on the first non null routing information found in a batch but using regular rules rather than rules for LWT queries, even if a LWT query was inside the batch.

Now LWT routing will be used for DefaultBatchStatements if somewhere along the way an LWT query was added to the batch. This can also be controlled explicitly regardless of batch contents with
`BatchStatementBuilder#setIsLWT(boolean)`.

Fixes: https://github.com/scylladb/java-driver/issues/488

### CODE REVIEW

**Comment by Bouncheck** [comment]
Fixes #488

**Comment by Bouncheck** [comment]
When I've checked the current implementation of BatchStatement it turned out that it already infers the routing information from the first query in a batch that has routing information. I've left that part as is and just added LWT support for batches according to suggestions.

File: core/src/test/java/com/datastax/oss/driver/internal/core/cql/DefaultBatchStatementTest.java [hunk 1]
```diff
@@ -97,4 +101,37 @@ public void should_not_issue_log_warn_if_statement_have_no_consistency_level_set
...
+    batchStatementBuilder.setIsLWT(true);
+    assertThat(batchStatementBuilder.build().isLWT()).isTrue();
+
+    assertThat(BatchStatement.newInstance(BatchType.UNLOGGED).isLWT()).isFalse();
+    assertThat(BatchStatement.newInstance(BatchType.LOGGED).isLWT()).isFalse();
+    assertThat(BatchStatement.newInstance(BatchType.COUNTER).isLWT()).isFalse();
+    assertThat(BatchStatement.newInstance(BatchType.UNLOGGED, lwtBoundStatement).isLWT()).isTrue();
+    assertThat(BatchStatement.newInstance(BatchType.LOGGED, lwtBoundStatement).isLWT()).isTrue();
+    assertThat(BatchStatement.newInstance(BatchType.COUNTER, lwtBoundStatement).isLWT()).isTrue();
+  }
```
Comment (Lorak-mmk) [inline core/src/test/java/com/datastax/oss/driver/internal/core/cql/DefaultBatchStatementTest.java]: Could you also add integration test that creates and executes batch that contains both LWT and non-LWT statements?

File: core/src/main/java/com/datastax/oss/driver/api/core/cql/BatchStatementBuilder.java [hunk 2]
```diff
@@ -155,10 +170,19 @@ public BatchStatement build() {
         serialConsistencyLevel,
         timeout,
         node,
-        nowInSeconds);
+        nowInSeconds,
+        resolveIsLWT(statements));
```
Comment (dkropachev) [inline core/src/main/java/com/datastax/oss/driver/api/core/cql/BatchStatementBuilder.java]: I think it would be better to do the following:
1. Make `isLWT null` by default
2. Unless you enforce it via `setIsLWT`it stays null
3. When you call `IsLWT()` if `isLWT` is `null` you resolves it via `resolveIsLWT`

It will help you with all the cases when you set `setIsLWT` and then manipulate with the batch.

File: core/src/test/java/com/datastax/oss/driver/internal/core/cql/DefaultBatchStatementTest.java (hunk 1 above)
Comment (dkropachev) [reply core/src/test/java/com/datastax/oss/driver/internal/core/cql/DefaultBatchStatementTest.java]: and test that would check that resulted LWT batch get routed properly.

File: core/src/main/java/com/datastax/oss/driver/api/core/cql/BatchStatementBuilder.java (hunk 2 above)
Comment (Bouncheck) [reply core/src/main/java/com/datastax/oss/driver/api/core/cql/BatchStatementBuilder.java]: It already is this way in `BatchStatementBuilder`. It's null by default and will stay like that until enforced. The value for instance of `BatchStatement` is only resolved at the final `build()`. There is no getter for `isLWT` in the builder.

Now in `DefaultBatchStatement` it's a normal boolean because it's immutable by design, so i think it makes sense to follow convention there and since it's supposed to be immutable there is no reason to resolve the value on each `isLWT()` call because it has to be the same all the time.

File: core/src/test/java/com/datastax/oss/driver/internal/core/cql/DefaultBatchStatementTest.java (hunk 1 above)
Comment (Bouncheck) [reply core/src/test/java/com/datastax/oss/driver/internal/core/cql/DefaultBatchStatementTest.java]: Will do

File: core/src/main/java/com/datastax/oss/driver/api/core/cql/BatchStatementBuilder.java (hunk 2 above)
Comment (dkropachev) [reply core/src/main/java/com/datastax/oss/driver/api/core/cql/BatchStatementBuilder.java]: It is immutable, but it has API that creates another copy of it with some changes.
In some cases behavior of this API becomes confusing, example:
```
   BatchStatement batch = new BatchStatementBuilder(BatchType.UNLOGGED).build();
    batch = batch.add(simpleStatement);
    assertThat(batch.isLWT()).isFalse();
    batch = batch.add(lwtBoundStatement);
    assertThat(batch.isLWT()).isTrue();
    batch = batch.clear();
    assertThat(batch.isLWT()).isFalse();
    batch = batch.add(simpleStatement);
    assertThat(batch.isLWT()).isFalse();
```
You would expect it to succeeded, but it fails, because `isLWT` is persisted.

Comment (Bouncheck) [reply core/src/main/java/com/datastax/oss/driver/api/core/cql/BatchStatementBuilder.java]: I left that this way because `clear` does not modify any other field either, but I guess it's true that it's weird in such case.
Would setting it to `false` on clear be acceptable? It would avoid `CqlRequestHandler` potential scan through the statement list.
If not I can make it `Boolean` and resolve on `isLWT()` method call the same way as in builder.

Comment (dkropachev) [reply core/src/main/java/com/datastax/oss/driver/api/core/cql/BatchStatementBuilder.java]: > I left that this way because `clear` does not modify any other field either, but I guess it's true that it's weird in such case. Would setting it to `false` on clear be acceptable? It would avoid `CqlRequestHandler` potential scan through the statement list. If not I can make it `Boolean` and resolve on `isLWT()` method call the same way as in builder.

I see you point, it is valid, but I still think it won't cut it, since creates another problem:
```
   BatchStatement batch = new BatchStatementBuilder(BatchType.UNLOGGED).setIsLWT(true).build();
    batch = batch.add(simpleStatement);
    batch = batch.add(lwtBoundStatement);
    batch = batch.clear();
    assertThat(batch.isLWT()).isTrue();
```
I think if user want to offload LWT resolution they just need to specify it via API, otherwise driver will have to do this job for them, btw we can throw a warning when driver resolves isLWT recomending them to set it specifically.

Comment (Bouncheck) [reply core/src/main/java/com/datastax/oss/driver/api/core/cql/BatchStatementBuilder.java]: I don't think it's a problem. In that case it's reasonably expected. 
Btw, is there a reason to run empty or non-lwt batch as LWT (which means different routing only)?

Comment (Bouncheck) [reply core/src/main/java/com/datastax/oss/driver/api/core/cql/BatchStatementBuilder.java]: Changed to Boolean in a newer version

Comment (dkropachev) [reply core/src/main/java/com/datastax/oss/driver/api/core/cql/BatchStatementBuilder.java]: You need to update the code not to touch isLWT and resolve it only when `isLWT()` is called

File: core/src/test/java/com/datastax/oss/driver/internal/core/cql/DefaultBatchStatementTest.java (hunk 1 above)
Comment (Bouncheck) [reply core/src/test/java/com/datastax/oss/driver/internal/core/cql/DefaultBatchStatementTest.java]: See if `LWTLoadBalancing#should_use_only_one_node_when_lwt_batch_detected` is sufficient. Basically the same as methods above it but for batch statement with non-LWT and LWT query.

**Comment by Bouncheck** [comment]
Adjusted integration test to have a batch with non-LWT and LWT query, added a few extra checks to unit test, adjusted docs and BatchStatement interface.

**Review by dkropachev — APPROVED** [review]

**Comment by Lorak-mmk** [comment]
I unfortunately still don't see an integration test that executes a batch with LWT and non-LWT statements. Could you add it in a separate PR?
Right now there is only a test that has both prepared and unprepared LWT statement.
