### PR TITLE
Fix NPE when closing a pool during initialization

### LINKED ISSUE #85: java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
Faced this issue once while playing with nosqlbench:

```
[cluster1-worker-0] ERROR com.datastax.cql3.scylla_shaded.driver.core.ExceptionCatchingRunnable - Unexpected error while executing task
java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
    at com.datastax.cql3.scylla_shaded.driver.core.HostConnectionPool.closeAsync(HostConnectionPool.java:841)
    at com.datastax.cql3.scylla_shaded.driver.core.SessionManager.removePool(SessionManager.java:440)
    at com.datastax.cql3.scylla_shaded.driver.core.SessionManager.onDown(SessionManager.java:528)
    at com.datastax.cql3.scylla_shaded.driver.core.Cluster$Manager.onDown(Cluster.java:2207)
    at com.datastax.cql3.scylla_shaded.driver.core.Cluster$Manager.access$1200(Cluster.java:1560)
    at com.datastax.cql3.scylla_shaded.driver.core.Cluster$Manager$5.runMayThrow(Cluster.java:2162)
    at com.datastax.cql3.scylla_shaded.driver.core.ExceptionCatchingRunnable.run(ExceptionCatchingRunnable.java:32)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at com.datastax.internal.com_google_common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
    at com.datastax.internal.com_google_common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
    at com.datastax.internal.com_google_common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:832)
[cqltabular2_default_schema:001] WARN com.datastax.cql3.scylla_shaded.driver.core.Session - Error creating pool to /10.0.2.65:9042
com.datastax.cql3.scylla_shaded.driver.core.exceptions.OperationTimedOutException: [/10.0.2.65:9042] Operation timed out
    at com.datastax.cql3.scylla_shaded.driver.core.Connection$Future.onTimeout(Connection.java:1642)
    at com.datastax.cql3.scylla_shaded.driver.core.Connection$ResponseHandler$1.run(Connection.java:1721)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:832)

```

### PR DESCRIPTION
**Pull request by dkropachev**
## Summary
Users reported the following failure during pool teardown:

`java.lang.NullPointerException: Cannot read the array length because "<local2>" is null`

at `com.datastax.cql3.scylla_shaded.driver.core.HostConnectionPool.closeAsync(HostConnectionPool.java:841)`.

This change:
- makes `HostConnectionPool.closeAsync()` tolerate pools that are still uninitialized or only partially initialized
- avoids publishing partially built shard arrays while initialization is still setting them up
- adds a regression test that closes an uninitialized pool and verifies shutdown completes cleanly

## Testing
- `mvn -pl driver-core -Dtest=HostConnectionPoolTest#should_close_uninitialized_pool_without_npe test`

Fixes #85.

### CODE REVIEW

File: driver-core/src/main/java/com/datastax/driver/core/HostConnectionPool.java [hunk 1]
```diff
@@ -301,19 +301,25 @@ ListenableFuture<Void> initAsyncWithConnection(Connection reusedConnection) {
...
+      openByShard[i] = new AtomicInteger();
+      trashByShard[i] = new CopyOnWriteArraySet<Connection>();
+      pendingBorrowsByShard[i] = new ConcurrentLinkedQueue<PendingBorrow>();
     }
 
+    this.connections = connectionsByShard;
+    scheduledForCreation = scheduledForCreationByShard;
+    open = openByShard;
+    trash = trashByShard;
+    pendingBorrows = pendingBorrowsByShard;
```
Comment (nikagra) [inline driver-core/src/main/java/com/datastax/driver/core/HostConnectionPool.java:321]: Race window still remains which may cause a partial initialization.

File: driver-core/src/main/java/com/datastax/driver/core/HostConnectionPool.java
Comment (nikagra) [inline driver-core/src/main/java/com/datastax/driver/core/HostConnectionPool.java:445]: According to Claude there is a chance `connections` can be null here, hardening recommended

File: driver-core/src/main/java/com/datastax/driver/core/HostConnectionPool.java (hunk 1 above)
Comment (dkropachev) [reply driver-core/src/main/java/com/datastax/driver/core/HostConnectionPool.java:321]: Yes, partial initialization is possible, unfortunately there is no good way to make it otherwise, what is impossible is to have any of `*ByShard` partially initialized, which is what addresses the problem, only thing that is rest now is to make sure that one is not null when it is addressed.

File: driver-core/src/main/java/com/datastax/driver/core/HostConnectionPool.java
Comment (dkropachev) [reply driver-core/src/main/java/com/datastax/driver/core/HostConnectionPool.java:445]: Impossible, as you can see it is a `HostConnectionPool.addCallback`, which is called on the bottom of `HostConnectionPool.initAsyncWithConnection`:
https://github.com/scylladb/java-driver/blob/758d17e3ee87609854bb6a40d4e19e118ef8cdd3/driver-core/src/main/java/com/datastax/driver/core/HostConnectionPool.java#L368

But that time `connections` is fully initialized`

**Review by nikagra — APPROVED** [review]
All concerns are addressed 👍
