### PR TITLE
4.x: Add advanced shard awareness

### LINKED ISSUE #515: 4.x: Advanced shard awareness
I've looked through the existing issues and haven't found any related specifically to implementing this feature.

Advanced shard awareness is a feature that speeds up connection creation. It uses Scylla's shard-aware port on which Scylla chooses target shard based on the connection's source port. AFAIK it was never implemented in 4.x version of the driver. 
3.x makes use of it by explicitly setting local port on `boostrap.connect(...)`:
https://github.com/scylladb/java-driver/blob/1ca5689aa665cea3e4013717b43b3115e78c57bd/driver-core/src/main/java/com/datastax/driver/core/Connection.java#L238
In 4.x it's not being used right now:
https://github.com/scylladb/java-driver/blob/de10f2f5ac8a8c84ed19313477521e8c9cf5d012/core/src/main/java/com/datastax/oss/driver/internal/core/channel/ChannelFactory.java#L207

Evidence for it not working right now:
Started 16 shard Scylla node and run 6 session initializations simultaneously. With 9042 port multiple reconnection attempts can be observed in debug logs before initializing full 16 channel pool. This is expected and was checked for reference.

With 19042 port it seems that driver gets stuck on 8/16 channels. This is a weird result, but if advanced shard awareness was in use it should not be happening either way. I was expecting a number of reconnections of the similar order as number of random d16 dice rolls until rolling every number.

Expected result with advanced shard awareness enabled would be driver initializing all channels without considerable number of reconnections for all sessions, ideally none.

### PR DESCRIPTION
**Pull request by Bouncheck**
Adds advanced shard awareness to the 4.x version of the driver.
Added integration test that checks if reconnections are sufficiently rare with advanced shard awareness.
`should_struggle_to_fill_pools` and `should_not_struggle_to_fill_pools` can be run locally to see the difference between the driver with and without this feature.

Fixes #515

### CODE REVIEW

**Comment by Bouncheck** [comment]
I'll probably introduce some small checks to port allocator (for example the range should not be too small) and some unit tests but the gist of the PR will probably look as it is now.

**Comment by dkropachev** [comment]
@Bouncheck , I realy don't like idea of `PortAllocator`, there is a gap between when you allocate port and create a socket, if by then port become busy, then connection attempt fails.
I have pushed one commit to address that, please take a look.

**Comment by Bouncheck** [comment]
> @Bouncheck , I realy don't like idea of `PortAllocator`, there is a gap between when you allocate port and create a socket, if by then port become busy, then connection attempt fails. I have pushed one commit to address that, please take a look.

There always is that possibility. PortIterator suffers from the same thing. The only solution is to try again.

From what I see PortIterator does not check if returned port was free at all.
Multiple instances use independent counters, which can result in more situations where connections snatch ports from each other. Note that PortAllocator uses global atomic counter, so subsequent calls will not return the same port number unless a very small range of free ports is given. 
I think out of the two I prefer the allocator.

**Comment by dkropachev** [comment]
> > @Bouncheck , I realy don't like idea of `PortAllocator`, there is a gap between when you allocate port and create a socket, if by then port become busy, then connection attempt fails. I have pushed one commit to address that, please take a look.
> 
> There always is that possibility. PortIterator suffers from the same thing. The only solution is to try again.
> 
> From what I see PortIterator does not check if returned port was free at all. Multiple instances use independent counters, which can result in more situations where connections snatch ports from each other. Note that PortAllocator uses global atomic counter, so subsequent calls will not return the same port number unless a very small range of free ports is given. I think out of the two I prefer the allocator.

It does that when socket is actually allocated, and no, it doesn't suffer from it, it will retry on next port if port is busy

**Comment by dkropachev** [comment]
@Bouncheck , also another reason to stick to PortIterator is that it keeps behavior inline with OS and driver socket configurations:
1. `DefaultDriverOption.SOCKET_REUSE_ADDRESS`
2. `UnixChannelOption.SO_REUSEPORT`
3. sysctl net.ipv4.tcp_tw_reuse

**Comment by Bouncheck** [comment]
> > > @Bouncheck , I realy don't like idea of `PortAllocator`, there is a gap between when you allocate port and create a socket, if by then port become busy, then connection attempt fails. I have pushed one commit to address that, please take a look.
> > 
> > 
> > There always is that possibility. PortIterator suffers from the same thing. The only solution is to try again.
> > From what I see PortIterator does not check if returned port was free at all. Multiple instances use independent counters, which can result in more situations where connections snatch ports from each other. Note that PortAllocator uses global atomic counter, so subsequent calls will not return the same port number unless a very small range of free ports is given. I think out of the two I prefer the allocator.
> 
> It does that when socket is actually allocated, and no, it doesn't suffer from it, it will retry on next port if port is busy

Both solutions are just black boxes that return an int when asked. In the time between they return an int and `bootstrap.connect(...)` is called the port with the same number can be stolen. So both do suffer from it and it cannot be really solved other than trying the whole process another time.

The additional bind exception handling you've added is separate from portIterator and can be done with any other port number picking black box as well, but it does not solve this problem (does not prevent stealing the port).

**Comment by Bouncheck** [comment]
> @Bouncheck , also another reason to stick to PortIterator is that it keeps behavior inline with OS and driver socket configurations:
> 
>     1. `DefaultDriverOption.SOCKET_REUSE_ADDRESS`
> 
>     2. `UnixChannelOption.SO_REUSEPORT`
> 
>     3. sysctl net.ipv4.tcp_tw_reuse

I don't understand this part

**Comment by dkropachev** [comment]
> > @Bouncheck , also another reason to stick to PortIterator is that it keeps behavior inline with OS and driver socket configurations:
> > ```
> > 1. `DefaultDriverOption.SOCKET_REUSE_ADDRESS`
> > 
> > 2. `UnixChannelOption.SO_REUSEPORT`
> > 
> > 3. sysctl net.ipv4.tcp_tw_reuse
> > ```
> 
> I don't understand this part

When you create a socket or bind it, the OS is generally expected to return an error if the specified port and/or address is already in use.
However, there are exceptions to this behavior, and they are influenced by two main factors:

Socket options:

`SO_REUSEPORT` and `SO_REUSEADDR` (exposed in Netty via `ChannelOption.SO_REUSEADDR` and `UnixChannelOption.SO_REUSEPORT`).

At least one of these is also configurable through the driver using `DefaultDriverOption.SOCKET_REUSE_ADDRESS`.

OS-level settings:

For example, on Linux, the sysctl setting `net.ipv4.tcp_tw_reuse`.

The outcome depends on the combination of `SO_REUSEPORT`, `SO_REUSEADDR`, `net.ipv4.tcp_tw_reuse`, and the current state of the address/port.
These rules differ between bind and listen operations.

Since you're calling listen first, the behavior will follow the rules specific to listen.

File: integration-tests/src/test/java/com/datastax/oss/driver/core/pool/AdvancedShardAwarenessIT.java [hunk 1]
```diff
@@ -0,0 +1,287 @@
...
+    appender.stop();
+    appender.list.clear();
+    channelPoolLogger.setLevel(originalLevelChannelPool);
+    reconnectionLogger.setLevel(originalLevelReconnection);
+    channelPoolLogger.detachAppender(appender);
+    reconnectionLogger.detachAppender(appender);
+  }
+
+  @Test
+  public void should_initialize_all_channels() {
```
Comment (dkropachev) [inline integration-tests/src/test/java/com/datastax/oss/driver/core/pool/AdvancedShardAwarenessIT.java]: Can you please add the test to connect to non-shard-aware port and check that it does not target shard-aware port for connection pool

File: core/src/main/java/com/datastax/oss/driver/api/core/config/DefaultDriverOption.java [hunk 2]
```diff
@@ -141,6 +141,17 @@ public enum DefaultDriverOption implements DriverOption {
    * <p>Value-type: boolean
    */
   CONNECTION_WARN_INIT_ERROR("advanced.connection.warn-on-init-error"),
+  /**
+   * Whether to use advanced shard awareness.
```
Comment (dkropachev) [inline core/src/main/java/com/datastax/oss/driver/api/core/config/DefaultDriverOption.java:145]: Can you please in short describe what is `advanced shardawarness`

File: core/src/main/resources/reference.conf [hunk 3]
```diff
@@ -535,6 +535,41 @@ datastax-java-driver {
     #   change.
     # Overridable in a profile: no
     warn-on-init-error = true
+
+
+    advanced-shard-awareness {
+      # Whether to use advanced shard awareness when trying to open new connections.
+      #
+      # Having this enabled makes sense only for ScyllaDB clusters.
+      # Results in smaller connection storms in multi-client settings.
```
Comment (dkropachev) [inline core/src/main/resources/reference.conf]: Does it ? I don't see any difference in this regard between regular shard awarness and advanced, if anything it will reduce number of reconnections needed to fullfill connection pool.

File: core/src/main/resources/reference.conf [hunk 4]
```diff
@@ -535,6 +535,41 @@ datastax-java-driver {
...
+      # If set to false the driver will not attempt to use this feature.
```
Comment (dkropachev) [inline core/src/main/resources/reference.conf]: Can you please change it to something like this: `if set to false the driver will not enforce local port on connection socket, counting on the fact that it eventually going to get connection to the shard it wants.`

File: core/src/main/resources/reference.conf [hunk 5]
```diff
@@ -535,6 +535,41 @@ datastax-java-driver {
...
+      # Modifiable at runtime: yes, the new value will be used for calls after the
+      # change.
+      port-low = 10000
+
+      # Inclusive upper bound of port range to use in advanced shard awareness.
+      # The driver will attempt to reserve ports for connection only within the range.
+      # Required: yes
+      # Modifiable at runtime: yes, the new value will be used for calls after the
+      # change.
+      port-high = 60000
```
Comment (dkropachev) [inline core/src/main/resources/reference.conf]: Why not 65535 ?

File: core/src/main/resources/reference.conf [hunk 6]
```diff
@@ -535,6 +535,41 @@ datastax-java-driver {
...
+      # Modifiable at runtime: yes, the new value will be used for connections created after the
+      # change.
+      # Overridable in a profile: no
+      enabled = true
+
+      # Inclusive lower bound of port range to use in advanced shard awareness
+      # The driver will attempt to reserve ports for connection only within the range.
+      # Required: yes
+      # Modifiable at runtime: yes, the new value will be used for calls after the
+      # change.
```
Comment (dkropachev) [inline core/src/main/resources/reference.conf:572]:
```suggestion
      # Modifiable at runtime: yes, the new value will be used for calls after the
      # change.
      # Overridable in a profile: no
```

File: core/src/main/resources/reference.conf [hunk 7]
```diff
@@ -535,6 +535,41 @@ datastax-java-driver {
...
+      port-low = 10000
+
+      # Inclusive upper bound of port range to use in advanced shard awareness.
+      # The driver will attempt to reserve ports for connection only within the range.
+      # Required: yes
+      # Modifiable at runtime: yes, the new value will be used for calls after the
+      # change.
```
Comment (dkropachev) [inline core/src/main/resources/reference.conf:580]:
```suggestion
      # Modifiable at runtime: yes, the new value will be used for calls after the
      # change.
      # Overridable in a profile: no
```

**Review by dkropachev — CHANGES_REQUESTED** [review]
LGTM, one more test needed and and couple of doc issues.

File: core/src/main/resources/reference.conf (hunk 3 above)
Comment (Bouncheck) [reply core/src/main/resources/reference.conf]: If it decreases the number of reconnections needed then it lessens the load, no? Of course all driver applications will need to use it for best results.
Maybe I'm using a wrong term here?

File: core/src/main/resources/reference.conf (hunk 5 above)
Comment (Bouncheck) [reply core/src/main/resources/reference.conf]: Copied it from 3.x. It's likely just an arbitrary, high range. I can set it to 65535

File: integration-tests/src/test/java/com/datastax/oss/driver/core/pool/AdvancedShardAwarenessIT.java (hunk 1 above)
Comment (Bouncheck) [reply integration-tests/src/test/java/com/datastax/oss/driver/core/pool/AdvancedShardAwarenessIT.java]: I'm not sure I understand what this is supposed to check exactly.
I think `should_see_mismatched_shard` already does that. It targets non-shard-aware port, and has new option enabled. It's verified by seeing the logs about the mismatch.

File: core/src/main/resources/reference.conf (hunk 6 above)
Comment (Bouncheck) [reply core/src/main/resources/reference.conf:572]: Added

File: core/src/main/resources/reference.conf (hunk 7 above)
Comment (Bouncheck) [reply core/src/main/resources/reference.conf:580]: Added.

File: core/src/main/resources/reference.conf (hunk 5 above)
Comment (Bouncheck) [reply core/src/main/resources/reference.conf]: Set to 65535

File: core/src/main/resources/reference.conf (hunk 4 above)
Comment (Bouncheck) [reply core/src/main/resources/reference.conf]: Added some extra text, although slightly different and linked blogpost about adv shard awareness

File: core/src/main/java/com/datastax/oss/driver/api/core/config/DefaultDriverOption.java (hunk 2 above)
Comment (Bouncheck) [reply core/src/main/java/com/datastax/oss/driver/api/core/config/DefaultDriverOption.java:145]: Added this part
```
      # In short it's a feature that allows targeting particular shard when connecting to a node by using specific
      # local port number.
```

**Comment by Bouncheck** [comment]
Addresed docs comments and added 1 change to port allocator. It will follow reuse address setting from the config.
Reasoning is that in theory port allocator using `false` all the time could prevent the driver from using some port that would actually work if reuse setting was respsected.

File: core/src/main/resources/reference.conf (hunk 3 above)
Comment (dkropachev) [reply core/src/main/resources/reference.conf]: Can you please refrase it so that it does not confuse.

Comment (Bouncheck) [reply core/src/main/resources/reference.conf]: Sure, but which part? I don't know which part is the problem

Comment (dkropachev) [reply core/src/main/resources/reference.conf]: `# Results in smaller connection storms in multi-client settings.` -> `# Enabling it reduces amount of reconnections driver does to get connection pool filled.`

Comment (Bouncheck) [reply core/src/main/resources/reference.conf]: changed to `Reduces number of reconnections driver needs to fully initialize connection pool.`

**Comment by Bouncheck** [comment]
Squashed fixes into appropriate commits and added missing `@RunWith(DataProviderRunner.class)`

**Review by dkropachev — APPROVED** [review]
